[versions]
androidTest = "1.4.0"
coroutines = "1.5.0"
junit4 = "4.13.1"
junit5 = "5.7.1"
kotlin = "1.5.31"
serialize = "1.2.2"

[libraries]
# android
androidCoreKtx = { module = "androidx.core:core-ktx", version = "1.8.0" }
annotation = { module = "androidx.annotation:annotation", version = "1.0.0" }
appCompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
contraintLayount = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.3" }
googleMaterial = { module = "com.google.android.material:material", version = "1.5.0" }

# dagger (sample app only)
hilt = { module = "com.google.dagger:hilt-android", version = "2.41" }
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version = "2.41" }
hiltCompiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }

# firebase
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics", version = "19.0.0" }

# kotlin
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialize" }
stdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }

# other
injectJavax = { module = "javax.inject:javax.inject", version = "1" }

## unit tests
androidJunitTestExt = { module = "androidx.test.ext:junit", version = "1.1.3" }
junit = { module = "junit:junit", version.ref = "junit4" }
mockk = { module = "io.mockk:mockk", version = "1.12.0" }
textEspresso = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
truth = { module = "com.google.truth:truth", version = "1.1" }

# instrumented tests
androidxTestRules = { module = "androidx.test:rules", version.ref = "androidTest" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidTest" }
jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }


